name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "Mk2OUP8rfHOn1MqdlhPt3j7FHcVXC5ByQUAQfhsw.zip"
  comment: "Resident.Evil.3.zip"
  url: https://download171.uploadhaven.com/1/application/zip/Mk2OUP8rfHOn1MqdlhPt3j7FHcVXC5ByQUAQfhsw.zip?key=VZdyM8Xpo-ztzzi2SRv82w&expire=1605265741&filename=Resident.Evil.3.zip
  file_name: "Resident.Evil.3.zip"
  piece_size: 25 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent